"""
modules/pdf_loader.py
=====================
Module for loading PDFs and splitting them into manageable text chunks.

Uses LangChain's PyPDFLoader and RecursiveCharacterTextSplitter to
prepare book content for embedding and retrieval.
"""

from typing import List, Dict, Any
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from config.settings import CHUNK_SIZE, CHUNK_OVERLAP


def load_and_split_pdf(file_path: str) -> List[Any]:
    """
    Loads a PDF file from the given path and splits it into text chunks.

    Args:
        file_path (str): The absolute path to the PDF file.

    Returns:
        List[Document]: A list of LangChain Document objects (chunks).
        Returns an empty list or raises error if the file cannot be processed.
    """
    try:
        # 1. Load the PDF document
        loader = PyPDFLoader(file_path)
        pages = loader.load()

        # 2. Initialize the text splitter with settings from config
        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=CHUNK_SIZE,
            chunk_overlap=CHUNK_OVERLAP,
            length_function=len,
            is_separator_regex=False,
        )

        # 3. Split the loaded pages into chunks
        chunks = text_splitter.split_documents(pages)
        return chunks

    except FileNotFoundError:
        print(f"❌ Error: File not found at {file_path}")
        return []
    except Exception as e:
        print(f"❌ Unexpected error loading PDF: {str(e)}")
        return []


def get_pdf_info(chunks: List[Any], file_path: str) -> Dict[str, Any]:
    """
    Returns basic metadata about the processed PDF for verification.

    Args:
        chunks (List): The list of chunks generated by load_and_split_pdf.
        file_path (str): Original file path to help with page extraction.
    """
    if not chunks:
        return {"pages": 0, "chunks": 0, "error": "No content processed"}

    # Get unique page numbers from the metadata of chunks
    total_pages = len(set(doc.metadata.get("page", 0) for doc in chunks))
    total_chunks = len(chunks)

    return {
        "file_name": file_path.split("\\")[-1],
        "total_pages": total_pages,
        "total_chunks": total_chunks
    }
